/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reservadevuelosvista;

import SistemaDeReserva.Conexion;
import SistemaDeReserva.Vuelo;
import SistemaDeReserva.VueloData;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class VistaVuelo extends javax.swing.JInternalFrame {
    private Vuelo vuelo;
    private VueloData vueloData;
    private Conexion conexion;
    
    /**
     * Creates new form VistaVuelo
     */
    public VistaVuelo() {
        try {
            initComponents();
            conexion = new Conexion("jdbc:mysql://localhost/reservadevuelos", "root", "");
            vueloData = new VueloData(conexion);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VistaVuelo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtCiudadDestino = new javax.swing.JTextField();
        jtCiudadDestino = new javax.swing.JLabel();
        txtCiudadOrigen = new javax.swing.JTextField();
        jtCiudadOrigen = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jtFecha = new javax.swing.JLabel();
        txtFechaLlegada = new javax.swing.JTextField();
        jtFechaLlegada = new javax.swing.JLabel();
        btGuardar = new javax.swing.JButton();
        btBorrar = new javax.swing.JButton();
        btLimpiar = new javax.swing.JToggleButton();
        btBuscar = new javax.swing.JToggleButton();
        jVuelo = new javax.swing.JLabel();
        txtAerolinea = new javax.swing.JTextField();
        jtAerolinea = new javax.swing.JLabel();
        txtAeronave = new javax.swing.JTextField();
        jtAeronave = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jtCiudadDestino.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jtCiudadDestino.setText("CIUDAD DESTINO");

        jtCiudadOrigen.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jtCiudadOrigen.setText("CIUDAD ORIGEN");

        jtFecha.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jtFecha.setText("FECHA-HORA PARTIDA");

        jtFechaLlegada.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jtFechaLlegada.setText("FECHA-HORA LLEGADA");

        btGuardar.setText("Guardar");
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });

        btBorrar.setText("Borrar");
        btBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBorrarActionPerformed(evt);
            }
        });

        btLimpiar.setText("Limpiar");
        btLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpiarActionPerformed(evt);
            }
        });

        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        jVuelo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jVuelo.setForeground(new java.awt.Color(0, 0, 153));
        jVuelo.setText("VUELOS");

        jtAerolinea.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jtAerolinea.setText("AEROLINEA");

        txtAeronave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAeronaveActionPerformed(evt);
            }
        });

        jtAeronave.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jtAeronave.setText("AERONAVE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btGuardar)
                        .addGap(26, 26, 26)
                        .addComponent(btBorrar)
                        .addGap(48, 48, 48)
                        .addComponent(btLimpiar)
                        .addGap(35, 35, 35)
                        .addComponent(btBuscar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtAeronave)
                            .addComponent(jtAerolinea)
                            .addComponent(jtCiudadDestino)
                            .addComponent(jtCiudadOrigen)
                            .addComponent(jtFecha)
                            .addComponent(jtFechaLlegada))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtCiudadDestino, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAerolinea, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAeronave, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFecha, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCiudadOrigen, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFechaLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jVuelo)
                        .addGap(20, 20, 20)))
                .addGap(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jVuelo)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtFechaLlegada)
                        .addComponent(txtFechaLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAerolinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtAerolinea))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtAeronave))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCiudadDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtCiudadDestino))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCiudadOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtCiudadOrigen))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtFecha))
                        .addGap(40, 40, 40)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btGuardar)
                    .addComponent(btBorrar)
                    .addComponent(btLimpiar)
                    .addComponent(btBuscar))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
        // TODO add your handling code here:
        String aerolinea=txtAerolinea.getText();
        LocalDate fechaPartida = LocalDate.parse(txtFecha.getText(),DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        LocalDate fechaLlegada = LocalDate.parse(txtFechaLlegada.getText(),DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        String aeronave=txtAeronave.getText();
        String ciudadOrigen=txtCiudadOrigen.getText();
        String ciudadDestino=txtCiudadDestino.getText();
        JOptionPane.showMessageDialog(null, fechaPartida);
        JOptionPane.showMessageDialog(null, fechaLlegada);
        vuelo = new Vuelo(ciudadOrigen,ciudadDestino,fechaPartida,fechaLlegada,aerolinea,aeronave);
        System.out.println("Aca");
        vueloData.guardarVuelo(vuelo);
        
    }//GEN-LAST:event_btGuardarActionPerformed

    private void btBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBorrarActionPerformed
        // TODO add your handling code here:
        //vueloData.borrarVuelo(WIDTH);

    }//GEN-LAST:event_btBorrarActionPerformed

    private void btLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpiarActionPerformed
        // TODO add your handling code here:
        jtAerolinea.setText(" ");
        jtFecha.setText(" ");
        jtFechaLlegada.setText(" ");
        jtCiudadOrigen.setText(" ");
        jtCiudadDestino.setText(" ");
        jtAeronave.setText(" ");

    }//GEN-LAST:event_btLimpiarActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        /*
        Vuelo vuelo = vueloData.buscarVuelo(WIDTH);
        jtAerolinea.setText(vuelo.getAerolinea());
        jtFecha.setText(vuelo.getFechaDePartida());
        jtFechaLlegada.setText(vuelo.getFechaDeLlegada().toString());
        jtCiudadOrigen.setText(vuelo.getCiudadDeOrigen());
        jtCiudadDestino.setText(vuelo.getCiudadDeDestino());
        jtAeronave.setText(vuelo.getAeronave());
        */

    }//GEN-LAST:event_btBuscarActionPerformed

    private void txtAeronaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAeronaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAeronaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBorrar;
    private javax.swing.JToggleButton btBuscar;
    private javax.swing.JButton btGuardar;
    private javax.swing.JToggleButton btLimpiar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jVuelo;
    private javax.swing.JLabel jtAerolinea;
    private javax.swing.JLabel jtAeronave;
    private javax.swing.JLabel jtCiudadDestino;
    private javax.swing.JLabel jtCiudadOrigen;
    private javax.swing.JLabel jtFecha;
    private javax.swing.JLabel jtFechaLlegada;
    private javax.swing.JTextField txtAerolinea;
    private javax.swing.JTextField txtAeronave;
    private javax.swing.JTextField txtCiudadDestino;
    private javax.swing.JTextField txtCiudadOrigen;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtFechaLlegada;
    // End of variables declaration//GEN-END:variables
}
